version: "3.8"
services:
  kms:
    image: "11notes/kms:latest"
    container_name: "postgres"
    environment:
      TZ: Europe/Zurich
    volumes:
      - "kms-var:/kms/var"
    networks:
      - kms
    restart: always
  whodb:
    image: "11notes/whodb:latest"
    container_name: "whodb"
    environment:
      TZ: Europe/Zurich
    volumes:
      - "kms-var:/whodb/var"
    ports:
      - "8080:8080/tcp"
    networks:
      - kms
      - frontend
    restart: always
volumes:
  kms-var:
networks:
  kms:
    internal: true
  frontend: