name: "kms"
services:
  kms:
    image: "11notes/kms:646f476"
    container_name: "kms"
    environment:
      TZ: Europe/Zurich
    volumes:
      - "var:/kms/var"
    ports:
      - "1688:1688/tcp"
    restart: always
volumes:
  var: