name: "kms"
services:
  kms:
    image: "11notes/kms:latest"
    container_name: "kms"
    environment:
      TZ: Europe/Zurich
    volumes:
      - "kms-var:/kms/var"
    restart: always
  whodb:
    image: "11notes/whodb:latest"
    container_name: "whodb"
    environment:
      TZ: Europe/Zurich
    volumes:
      - "kms-var:/whodb/var"
    ports:
      - "8080:8080/tcp"
    restart: always
volumes:
  kms-var: