name: readme

on:
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: update README.md
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          wait-for-completion: false
          workflow: docker.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "build":"false", "release":"false", "readme":"true" }'